### ISSUE TITLE
Which Version of Simulator SDK?

### ISSUE THREAD

**Issue by ahmedyarub** [omichel/naoqisim#1]
here can I download the latest version of the Simulator SDK?
The only one I could find was simulator-sdk-2.1.2.17-win32-vs2010, and it gives the following error:
1>d:\fady\simulator-sdk-2.1.2.17-win32-vs2010\include\qi\path.hpp(50): warning C4251: 'qi::Path::_p': class 'boost::shared_ptr<qi::PrivatePath>' needs to have dll-interface to be used by clients of class 'qi::Path'
1>d:\fady\simulator-sdk-2.1.2.17-win32-vs2010\include\qi\path.hpp(49): note: see declaration of 'boost::shared_ptr<qi::PrivatePath>'
1>d:\fady\naoqisim\controllers\naoqisim\singletons.cpp(81): error C2660: 'Sim::SimLauncher::launch': function does not take 5 arguments
1>d:\fady\simulator-sdk-2.1.2.17-win32-vs2010\include\alsimutils\sim_launcher.h(34): note: see declaration of 'Sim::SimLauncher::launch'

I could compile it by removing the last parameter of the line:
return mLauncher->launch(mModel, naoqiPort, wbu_system_short_path(sdkPrefix.c_str()), std::vector<std::string>(), halInitializedCallback);

But it doesn't look like I have the same version of naosim used here

**Comment by omichel** [comment]
The version of the Simulator SDK should be 2.1.4.1 as you can see in the this file:
https://github.com/omichel/naoqisim/blob/master/aldebaran/Makefile

This Makefile will normally download the correct version of the Simulator SDK and setup everything so that the compilation of naoqisim should be very smooth.

Let me know if you experience any problem.

**Comment by ahmedyarub** [comment]
is that Makefile used by Visual Studio solutions, too?
Because in my case I had to manually download everything...

**Comment by omichel** [comment]
No, this Makefile is not used by Visual Studio. It is used my "make" from the MSYS2 environment (see the explanations on development environment at https://github.com/omichel/naoqisim/blob/master/README.md)
